name: Documentation request
description: A request for new or updated documentation.
labels: A-docs
body:
  - type: textarea
    attributes:
      label: What pages are affected?
  - type: textarea
    attributes:
      label: What needs to be changed or added?
  - type: textarea
    attributes:
      label: Feature description
  - type: input
    attributes:
      label: Engineering tracking ticket
  - type: textarea
    attributes:
      label: Design documents
      description: |
        Please link any available design documents, like technical specs, product specs, or test files.
